### ISSUE TITLE
Einthusan not working after site updates

### ISSUE THREAD

**Issue by rdudeja1133** [coder-alpha/Einthusan.bundle#12]
Einthusan not working after site updates

**Comment by crecripadr** [comment]
re: https://forums.plex.tv/discussion/comment/1320998/#Comment_1320998

Checking the site, I could infer that site has SNI enabled i.e more than one cert loaded. I believe this is because both `einthusan.com` and `einthusan.tv` are still available
`openssl s_client -connect einthusan.tv:443 -tls1`

Run this command to pick the cert from `einthusan.tv` only
openssl s_client -connect einthusan.tv:443 -tls1 -servername einthusan.tv

You got to check what HTTP package you are using in python. recommended to use `requests` latest version to get SNI support.

(BTW keep up the good work)

**Comment by coder-alpha** [comment]
Thanks @crecripadr It seems the latest PMS version for Windows does have Python with the required module. However, I found the same PMS version for Linux giving the TLS error.

Please read the instruction on the Plex forum thread and then try v0.08 tested as of now on Win10.
